### ISSUE TITLE
[Bug] [Radon?] Chunks not generating properly

### ISSUE THREAD

**Issue by Vapaman** [Asek3/Rubidium#137]
Since there doesn't seem to be a issue page for radon, I'm putting this here. Also I'm not quite sure if its radon, but the issue didn't happen when the mod is disabled.

**Description:**
Chunks do not load properly after some time.

To replicate, fly in creative mod in a world loading chunks for some time, and they start to not load.
![2022-05-29_18 44 33](https://user-images.githubusercontent.com/77460466/170881133-1ee3a802-c2c1-497d-96c4-39793d9e3802.png)

Log:

[2022-05-28-2.log](https://github.com/Asek3/Rubidium/files/8793796/2022-05-28-2.log)

Particularly:
`[18:46:32] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalArgumentException: No value with id -1
	at net.minecraft.core.IdMap.m_200957_(IdMap.java:19) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.world.level.chunk.LinearPalette.m_5680_(LinearPalette.java:82) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.world.level.chunk.PalettedContainer.m_63118_(PalettedContainer.java:150) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.world.level.chunk.LevelChunkSection.m_63004_(LevelChunkSection.java:170) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_187971_(LevelChunk.java:431) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.client.multiplayer.ClientChunkCache.m_194116_(ClientChunkCache.java:97) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_194198_(ClientPacketListener.java:605) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_183388_(ClientPacketListener.java:600) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5797_(ClientboundLevelChunkWithLightPacket.java:45) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5797_(ClientboundLevelChunkWithLightPacket.java:12) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1013) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23116!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.25.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]`

**Comment by Gbergz** [comment]
I've gotten this particular issue on an NVIDIA gpu aswell.

**Comment by ovingiv** [comment]
I've gotten this on single player worlds. However, playing on a dedicated server this does not happen. NVIDIA gpu.
