### ISSUE TITLE
Crash upon joining world ("arenaMemoryAllocator is null")

### ISSUE THREAD

**Issue by Speeder323** [Asek3/Rubidium#198]
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/20/22, 2:26 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.gui.SodiumGameOptions$ArenaMemoryAllocator.ordinal()" because "me.jellysquid.mods.sodium.client.SodiumClientMod.options().advanced.arenaMemoryAllocator" is null
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegion$RenderRegionArenas.createArena(RenderRegion.java:194) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegion$RenderRegionArenas.<init>(RenderRegion.java:154) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.createRegionArenas(RenderRegionManager.java:178) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegion.getOrCreateArenas(RenderRegion.java:98) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:103) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:63) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.performPendingUploads(RenderSectionManager.java:379) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:323) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:197) ~[rubidium-0.5.3.jar%2370!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java:4134) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1157) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1045) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:664) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.68.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegion$RenderRegionArenas.createArena(RenderRegion.java:194) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegion$RenderRegionArenas.<init>(RenderRegion.java:154) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.createRegionArenas(RenderRegionManager.java:178) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegion.getOrCreateArenas(RenderRegion.java:98) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:103) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:63) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.performPendingUploads(RenderSectionManager.java:379) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:323) ~[rubidium-0.5.3.jar%2370!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:197) ~[rubidium-0.5.3.jar%2370!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java:4134) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1157) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['RawEgg_'/68808, l='ClientLevel', x=5.32, y=99.55, z=-259.69]]
	Chunk stats: 4096, 921
	Level dimension: minecraft:the_nether
	Level spawn location: World: (272,67,-96), Section: (at 0,3,0 in 17,4,-6; chunk contains blocks 272,0,-96 to 287,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 21615017 game time, 23939939 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2261) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:686) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.68.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, Supplementaries Generated Pack

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 687198728 bytes (655 MiB) / 1879048192 bytes (1792 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 4600
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0412
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4835
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 17828.11
	Virtual memory used (MB): 10375.87
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 483.09
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.1.68
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Intel(R) HD Graphics 4600 GL version 3.2.0 - Build 20.19.15.4835, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.2-1.1.2.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Amplified_Nether_v1.1.1.jar                       |Amplified Nether              |amplifiednether               |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.18.2-2.2.51.jar                 |Simple Voice Chat             |voicechat                     |1.18.2-2.2.51       |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.3.jar                       |Jade                          |jade                          |5.2.3               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.0.209.jar                          |Just Enough Items             |jei                           |9.7.0.209           |DONE      |Manifest: NOSIGNATURE
		mmlib-1.0.5-1.18.2.jar                            |Mysterious Mountain Lib       |mmlib                         |1.0.5-1.18.2        |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.3.jar                                |Rubidium                      |rubidium                      |0.5.3               |DONE      |Manifest: NOSIGNATURE
		Craftable+Saddles+[1.18+All]-1.4.jar              |Craftable Saddles             |craftable_saddles             |1.4                 |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.4.jar                     |Flywheel                      |flywheel                      |1.18-0.6.4.87       |DONE      |Manifest: NOSIGNATURE
		FarmersRespite-1.18.2-1.3.0.jar                   |Farmer's Respite              |farmersrespite                |1.18.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.2-1.0.6.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.2_v0.5.0c.jar                       |Create                        |create                        |0.5.0c              |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18.2-FORGE-2.0.5.jar                  |Croptopia                     |croptopia                     |2.0.5               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.8.5-forge (1).jar             |Journeymap                    |journeymap                    |5.8.5               |DONE      |Manifest: NOSIGNATURE
		Serene+Seasons-1.18.2-7.0.0.13.jar                |Serene Seasons                |sereneseasons                 |1.18.2-7.0.0.13     |DONE      |Manifest: NOSIGNATURE
		xercapaint-1.18.2-0.7.1.jar                       |Joy of Painting               |xercapaint                    |1.18.2-0.7.1        |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.18.2-20220308a.jar             |Builders Crafts & Addition    |buildersaddition              |1.18.2-20220308a    |DONE      |Manifest: NOSIGNATURE
		corn_delight-1.0.4-1.18.2.jar                     |Corn Delight                  |corn_delight                  |1.0.4-1.18.2        |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.2.1a.jar                             |Terralith                     |terralith                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.18.2-2.2.0.jar                       |Jade Addons                   |jadeaddons                    |2.2.0               |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.18.2-3.5.3.jar                      |FallingTree                   |fallingtree                   |3.5.3               |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		forge-1.18.2-40.1.68-universal.jar                |Forge                         |forge                         |40.1.68             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		xercamusic-1.18.2-1.0.0.jar                       |Xerca's Music Maker Mod       |xercamusic                    |1.18.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.4.8.jar                  |Supplementaries               |supplementaries               |1.18.2-1.4.8        |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: d1a340e7-33c8-4d34-a06c-ed399fdad5e4
	FML: 40.1
	Forge: net.minecraftforge:40.1.68
```

**Comment by asodugf12** [comment]
I think Rubidium doesn't work with forge 40.1.0 and above

**Comment by asodugf12** [comment]
big bummer tbh

**Comment by Asek3** [comment]
Just update rubidium and forge
