### ISSUE TITLE
Semi-random crashes related to particle rendering on world join

### ISSUE THREAD

**Issue by copygirl** [Asek3/Rubidium#226]
Some friends of mine are somewhat consistently (but not always) getting crashes when connecting to our server. The issue seems to not occur when Rubidium is disabled. With the default settings, they get a "Process crashed with exitcode -1073740940.". When looking into the options available, I decided to tell them to turn off the "Allow Direct Memory Access" option. This resulted in getting a proper error and crash log.

Currently we can't do further testing, especially as this is not a problem I am running into.

### Versions

**Minecraft:** `1.18.2`
**Forge:** `40.1.68`
**Rubidium:** `0.5.3`
Many more mods, see log?

### Crash Log

```
[18:13:53] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.ReportedException: Rendering Particle
	at net.minecraft.client.particle.ParticleEngine.render(ParticleEngine.java:420) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.particle.cull.MixinParticleManager,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.ParticleManagerAccess,pl:mixin:APP:create.mixins.json:accessor.ParticleEngineAccessor,pl:mixin:A,pl:runtimedistcleaner:A}{re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1370) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	[...]
Caused by: java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:749) ~[?:?] {re:mixin}
	at java.nio.DirectByteBuffer.putInt(DirectByteBuffer.java:725) ~[?:?] {}
	at me.jellysquid.mods.sodium.client.model.vertex.formats.particle.writer.ParticleVertexBufferWriterNio.writeParticle(ParticleVertexBufferWriterNio.java:26) ~[rubidium-0.5.3.jar%23175!/:?] {re:classloading}
	at net.minecraft.client.particle.SingleQuadParticle.addVertex(SingleQuadParticle.java:618) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.particle.fast_render.MixinBillboardParticle,pl:mixin:A}
	[...]
```
[Full PolyMC log.](https://mclo.gs/E5kYo9o)

**Comment by copygirl** [comment]
Curious if this has to do with SammySemicolon/Malum-Mod#109. That error I was able to reproduce by just being close to one of Malum's totems while activated (or, according to other player, using the scythe to kill a mod?). However the crash is very different:
```
java.lang.IllegalArgumentException: newLimit > capacity: (1792 > 1536)
	at java.nio.Buffer.createLimitException(Buffer.java:395) ~[?:?] {re:mixin}
	at java.nio.Buffer.limit(Buffer.java:369) ~[?:?] {re:mixin}
	at java.nio.ByteBuffer.limit(ByteBuffer.java:1529) ~[?:?] {re:mixin}
	at java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:330) ~[?:?] {}
	at java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:73) ~[?:?] {}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_85728_(BufferBuilder.java:329) ~[client-1.18.2-20220404.173914-srg.jar%23230!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:core.pipeline.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder_SegmentRendering,pl:mixin:APP:mixins.oculus.vertexformat.json:MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo,pl:mixin:APP:flywheel.mixins.json:BufferBuilderMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:vertex_format.entity.MixinBufferBuilder_ExtendedVertexFormatCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.BufferUploader.m_85761_(BufferUploader.java:50) ~[client-1.18.2-20220404.173914-srg.jar%23230!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:BufferUploaderMixin,pl:mixin:A}
	at net.minecraft.client.renderer.RenderType.m_110412_(RenderType.java:368) ~[client-1.18.2-20220404.173914-srg.jar%23230!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109912_(MultiBufferSource.java:96) ~[client-1.18.2-20220404.173914-srg.jar%23230!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorMultiBufferSource,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferSource,pl:mixin:APP:mixins.oculus.vertexformat.json:immediate.MixinBufferSource,pl:mixin:A}
	at com.sammy.ortus.handlers.RenderHandler.renderLast(RenderHandler.java:43) ~[ortus-1.18.2-1.0.jar%23177!/:1.18.2-1.0] {re:classloading}
	at com.sammy.ortus.events.ClientRuntimeEvents.renderLast(ClientRuntimeEvents.java:46) ~[ortus-1.18.2-1.0.jar%23177!/:1.18.2-1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_94_ClientRuntimeEvents_renderLast_RenderLevelLastEvent.invoke(.dynamic) ~[?:?] {}
	[...]
```
