### ISSUE TITLE
crash when entering overworld [1.16.5]

### ISSUE THREAD

**Issue by Zypher0725** [Asek3/Rubidium#257]
It goes normally when rubidium removed. Also even somehow successfully get into the world, the generation crashed some blocks don't show up and some appears in the sky.

![圖片_2022-08-29_012146631](https://user-images.githubusercontent.com/34536446/187086641-1b2e4ef6-04b3-4d04-bc8e-1e5d4e627d98.png)

[crash-2022-08-28_22.35.38-client.txt](https://github.com/Asek3/Rubidium/files/9439870/crash-2022-08-28_22.35.38-client.txt)

**Comment by coderepo8593** [comment]
1. Disable the sky renderer for Astral Sorcery.
2. You are using and older version of BetterEnd that is incompatible. Use BetterEnd Reforked

If that doesn't fix it, the next most likely place to look is the other render mixins. They are included in the stack trace for the associated call. You can see that is where I saw that Astral Sorcery and BetterEnd was getting involved. This is unlikely to be a problem with Rubidium itself and instead a problem with one of those other mods.

This looks like it is a known issue with Astral Sorcery or using the broken adn outdated forgeport version of BetterEnd.

	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:client.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dark_caverns.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dark_caverns.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by Kasualix** [comment]
rubidium is incompatible and will never compatible with optifine!
銣與高清修復不兼容，也永遠不會與高清修復兼容！

**Comment by Asek3** [comment]
Crash-report is related to helium, not rubidium.
However to fix bug BetterEnd needs to be updated to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files/3523090
