### ISSUE TITLE
Rubidium is incompatible with Forgery (Forge port of Fabrication)

### ISSUE THREAD

**Issue by coderepo8593** [Asek3/Rubidium#262]
https://www.curseforge.com/minecraft/mc-mods/forgery

[02:49:35] [main/FATAL]: Unreported exception thrown!
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1926) ~[?:1.8.0_51]
	at me.jellysquid.mods.sodium.common.util.collections.FutureDequeDrain.findNext(FutureDequeDrain.java:33) ~[?:?]
	at me.jellysquid.mods.sodium.common.util.collections.FutureDequeDrain.hasNext(FutureDequeDrain.java:23) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.backends.multidraw.MultidrawChunkRenderBackend.setupUploadBatches(MultidrawChunkRenderBackend.java:235) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.backends.multidraw.MultidrawChunkRenderBackend.upload(MultidrawChunkRenderBackend.java:114) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:459) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:205) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:4763) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:936) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$499/74259289.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.biome.BiomeColors.handler$zid000$be_getWaterColor(SourceFile:540) ~[?:?]
	at net.minecraft.world.biome.BiomeColors.func_228363_c_(SourceFile:26) ~[?:?]
	at net.minecraftforge.fluids.FluidAttributes$Water.getColor(FluidAttributes.java:432) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.lambda$static$0(FluidRenderer.java:42) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer$$Lambda$29567/2023339312.getColor(Unknown Source) ~[?:?]
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getBlockColor(SmoothBiomeColorBlender.java:49) ~[?:?]
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getInterpolatedVertexColor(SmoothBiomeColorBlender.java:71) ~[?:?]
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getColors(SmoothBiomeColorBlender.java:30) ~[?:?]
	at me.jellysquid.mods.sodium.client.model.quad.blender.ConfigurableColorBlender.getColors(ConfigurableColorBlender.java:34) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.calculateQuadColors(FluidRenderer.java:361) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.render(FluidRenderer.java:201) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:137) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:291) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51]

[02:49:36] [main/ERROR]: Unhandled game exception
net.minecraft.crash.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:505) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?]
	at net.minecraft.client.Minecraft.func_213241_c(Minecraft.java:1943) ~[?:?]
	at net.minecraft.client.Minecraft.func_213231_b(Minecraft.java:1911) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.cleanupBeforeMinecraft(InGameCatcher.java:52) ~[?:?]
	at net.minecraft.client.Minecraft.handler$bld000$beforeCleanUpAfterCrash(Minecraft.java:7067) ~[?:?]
	at net.minecraft.client.Minecraft.func_71398_f(Minecraft.java) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:630) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$499/74259289.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_51]
	at net.coderbot.iris.uniforms.CommonUniforms.lambda$generalCommonUniforms$4(CommonUniforms.java:108) ~[?:?]
	at net.coderbot.iris.uniforms.CommonUniforms$$Lambda$29478/1462589026.getAsDouble(Unknown Source) ~[?:?]
	at net.coderbot.iris.gl.uniform.LocationalUniformHolder.lambda$uniform1f$3(LocationalUniformHolder.java:37) ~[?:?]
	at net.coderbot.iris.gl.uniform.LocationalUniformHolder$$Lambda$29387/1275631955.getAsFloat(Unknown Source) ~[?:?]
	at net.coderbot.iris.gl.uniform.FloatUniform.updateValue(FloatUniform.java:30) ~[?:?]
	at net.coderbot.iris.gl.uniform.FloatUniform.update(FloatUniform.java:22) ~[?:?]
	at net.coderbot.iris.gl.program.ProgramUniforms.updateStage(ProgramUniforms.java:50) ~[?:?]
	at net.coderbot.iris.gl.program.ProgramUniforms.update(ProgramUniforms.java:70) ~[?:?]
	at net.coderbot.iris.gl.program.Program.use(Program.java:23) ~[?:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline$Pass.use(DeferredWorldRenderingPipeline.java:704) ~[?:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.beginPass(DeferredWorldRenderingPipeline.java:534) ~[?:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.matchPass(DeferredWorldRenderingPipeline.java:519) ~[?:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.syncProgram(DeferredWorldRenderingPipeline.java:1036) ~[?:?]
	at com.mojang.blaze3d.platform.GlStateManager$$Lambda$3114/1399313519.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at com.mojang.blaze3d.platform.GlStateManager.handler$zof000$iris$beforeDrawArrays(GlStateManager.java:5910) ~[?:?]
	at com.mojang.blaze3d.platform.GlStateManager.func_227719_f_(GlStateManager.java) ~[?:?]
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_227844_a_(SourceFile:46) ~[?:?]
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(SourceFile:24) ~[?:?]
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:28) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.func_231165_f_(Screen.java:368) ~[?:?]
	at net.minecraft.client.gui.screen.DirtMessageScreen.func_230430_a_(SourceFile:18) ~[?:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:363) ~[?:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:356) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?]
	... 19 more

**Comment by coderepo8593** [comment]
It crashes either as soon as it joins the world before being able to see the world render or shortly after the world has rendered. When I see water, it does not render at all and I instead I get an xray vision effect.

**Comment by coderepo8593** [comment]
I have created this issue on Forgery's(Fabrication) issue tracker
https://github.com/unascribed/Fabrication/issues/539

**Comment by Asek3** [comment]
Fixed on latest versions

**Comment by subzerohurley** [comment]
I dont even have forgery and I'm getting the same crash
