### ISSUE TITLE
unexpected crash in 1.16.5

### ISSUE THREAD

**Issue by ink717** [Asek3/Rubidium#280]
using latest version (0.2.10) in forge 34.2.39
[crash-2022-09-18_12.35.23-client.txt](https://github.com/Asek3/Rubidium/files/9594428/crash-2022-09-18_12.35.23-client.txt)

**Comment by coderepo8593** [comment]
I think I will put the same effort looking into this issue as you took in describing it.

EDIT:
On second thought, I'll be nice. Make sure you disable the SkyRendering in Astral Sorcery, is will cause a crash.

If something else is going on, I don't know because you didn't give us the circumstances under which it is crashing.

**Comment by ink717** [comment]
in this case, the crash is still considered "rare" and I need to "bet" it happens more often so more detailed and useful information can be provided :(
I'll update ANYTHING in detail if it happened again

**Comment by ink717** [comment]
[crash-2022-09-29_03.05.18-client.txt](https://github.com/Asek3/Rubidium/files/9671952/crash-2022-09-29_03.05.18-client.txt)

another crash - this time with a crash log. 
it might also related to #279 and #237 ?

**Comment by ink717** [comment]
both crash happened in vicinity of where chisel and bit's block exists.
also a potential relation  - with the train tracks (immersive railroading)
and shaders isn't on. 
both in creative mode and flying - constantly changing view area

also don't know whether this is any helpful, but this is constantly spamming the console whenever moving toward a new chunk

[29/09/2022 03:25:30 AM] [main/FATAL] Error executing task on Client
[29/09/2022 03:25:30 AM] 	at net.minecraft.network.datasync.EntityDataManager.func_187224_a(EntityDataManager.java:245)
[29/09/2022 03:25:30 AM] 	at net.minecraft.network.datasync.EntityDataManager.func_187218_a(EntityDataManager.java:233)
[29/09/2022 03:25:30 AM] 	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147284_a(ClientPlayNetHandler.java:552)
[29/09/2022 03:25:30 AM] 	at net.minecraft.network.play.server.SEntityMetadataPacket.func_148833_a(SourceFile:42)
[29/09/2022 03:25:30 AM] 	at net.minecraft.network.play.server.SEntityMetadataPacket.func_148833_a(SourceFile:11)
[29/09/2022 03:25:30 AM] 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
[29/09/2022 03:25:30 AM] 	at net.minecraft.network.PacketThreadUtil$$Lambda$31167/226696083.run(Unknown Source)
[29/09/2022 03:25:30 AM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[29/09/2022 03:25:30 AM] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[29/09/2022 03:25:30 AM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[29/09/2022 03:25:30 AM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
[29/09/2022 03:25:30 AM] 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948)
[29/09/2022 03:25:30 AM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[29/09/2022 03:25:30 AM] 	at net.minecraft.client.main.Main.main(Main.java:184)
[29/09/2022 03:25:30 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[29/09/2022 03:25:30 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[29/09/2022 03:25:30 AM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[29/09/2022 03:25:30 AM] 	at java.lang.reflect.Method.invoke(Method.java:497)
[29/09/2022 03:25:30 AM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[29/09/2022 03:25:30 AM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/1513124396.call(Unknown Source)
[29/09/2022 03:25:30 AM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[29/09/2022 03:25:30 AM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[29/09/2022 03:25:30 AM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[29/09/2022 03:25:30 AM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[29/09/2022 03:25:30 AM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

**Comment by Asek3** [comment]
Will be fixed in next release.
https://github.com/Asek3/Rubidium/commit/619abd622ac3856431a79a1ccda710ea20a95c31
