### ISSUE TITLE
Crash 1.16.5 with Alex's Mobs

### ISSUE THREAD

**Issue by LasthopeBR** [Asek3/Rubidium#299]
Player reporting Rendering entity in world
forge 36.2.39 Multiplayer

Crashlog: https://hastebin.com/gikawowobi.rb

**Comment by coderepo8593** [comment]
This is what I think to be the most relevant portion

`at net.minecraft.client.renderer.FirstPersonRenderer.func_228397_a_(FirstPersonRenderer.java:50) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.1,xf:fml:forge:crossbows.0,xf:fml:forge:crossbows.1,xf:fml:forge:filled_map.0,pl:mixin:APP:tac.mixins.json:client.FirstPersonRendererMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorFirstPersonRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mrcrayfish.obfuscate.client.Hooks.fireRenderHeldItem(Hooks.java:57) ~[obfuscate:0.6.3-1.16.5] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.layers.HeldItemLayer.redirect$zna000$fireRenderHeldItem(SourceFile:521) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:obfuscate.mixins.json:client.HeldItemLayerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.layers.HeldItemLayer.func_229135_a_(SourceFile:61) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:obfuscate.mixins.json:client.HeldItemLayerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.layers.HeldItemLayer.func_225628_a_(SourceFile:39) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:obfuscate.mixins.json:client.HeldItemLayerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.layers.HeldItemLayer.func_225628_a_(SourceFile:15) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:obfuscate.mixins.json:client.HeldItemLayerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:125) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium-extra.mixins.json:render.entity.MixinLivingEntityRenderer,pl:mixin:APP:moreplayermodels.mixins.json:LivingRendererMixin,pl:mixin:APP:obfuscate.mixins.json:client.LivingRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:mixin,xf:fml:forge:crossbows.2,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:APP:abnormals_core.mixins.json:client.PlayerRendererMixin,pl:mixin:APP:mixins.artifacts.json:render.PlayerRendererMixin,pl:mixin:APP:randompatches.mixins.json:client.PlayerRendererMixin,pl:mixin:APP:moreplayermodels.mixins.json:PlayerRendererMixin,pl:mixin:APP:expandability.mixins.json:swimming.client.PlayerRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:mixin,xf:fml:forge:crossbows.2,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:APP:abnormals_core.mixins.json:client.PlayerRendererMixin,pl:mixin:APP:mixins.artifacts.json:render.PlayerRendererMixin,pl:mixin:APP:randompatches.mixins.json:client.PlayerRendererMixin,pl:mixin:APP:moreplayermodels.mixins.json:PlayerRendererMixin,pl:mixin:APP:expandability.mixins.json:swimming.client.PlayerRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}`

Possible moreplayermodels, or some kind of interaction going wrong with Expandability and Obfuscate.
