### ISSUE TITLE
NullPointerException at  net.minecraft.world.biome.BiomeColors.handler$zhg000$getWaterColor(SourceFile:558)

### ISSUE THREAD

**Issue by peter-ahe** [Asek3/Rubidium#302]
```log
Caused by: java.lang.NullPointerException
	at net.minecraft.world.biome.BiomeColors.handler$zhg000$getWaterColor(SourceFile:558) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:BiomeColorsMixin,pl:mixin:A}
	at net.minecraft.world.biome.BiomeColors.func_228363_c_(SourceFile:26) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:BiomeColorsMixin,pl:mixin:A}
	at net.minecraftforge.fluids.FluidAttributes$Water.getColor(FluidAttributes.java:446) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.lambda$static$0(FluidRenderer.java:42) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getBlockColor(SmoothBiomeColorBlender.java:49) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getInterpolatedVertexColor(SmoothBiomeColorBlender.java:71) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getColors(SmoothBiomeColorBlender.java:30) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.model.quad.blender.ConfigurableColorBlender.getColors(ConfigurableColorBlender.java:34) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.calculateQuadColors(FluidRenderer.java:361) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.render(FluidRenderer.java:201) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:137) ~[?:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:291) ~[?:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_74] {}
```

[crash-2022-10-02_08.25.23-client.txt](https://github.com/Asek3/Rubidium/files/9691900/crash-2022-10-02_08.25.23-client.txt)

**Comment by peter-ahe** [comment]
Work around: disable biome blending.

**Comment by Asek3** [comment]
Update BetterEnd to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files/3523090
