### ISSUE TITLE
[1.16.5] Crash with Epic Fight

### ISSUE THREAD

**Issue by SettingDust** [Asek3/Rubidium#402]
Is there an option can avoid this? Or will it be fixed?
```
java.lang.IllegalArgumentException: Duplicate delegates
	at com.mojang.blaze3d.vertex.VertexBuilderUtils$DelegatingVertexBuilder.<init>(SourceFile:29) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.vertex.VertexBuilderUtils.func_227915_a_(SourceFile:15) ~[?:?] {re:mixin,re:classloading}
	at yesman.epicfight.client.renderer.ModRenderTypes.getArmorVertexBuilder(ModRenderTypes.java:142) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.layer.WearableItemLayer.renderArmor(WearableItemLayer.java:42) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.layer.WearableItemLayer.renderLayer(WearableItemLayer.java:83) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.layer.WearableItemLayer.renderLayer(WearableItemLayer.java:32) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.layer.AnimatedLayer.renderLayer(AnimatedLayer.java:17) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.renderer.entity.ArmatureRenderer.lambda$renderLayer$0(ArmatureRenderer.java:136) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
```

**Comment by Asek3** [comment]
Related to Oculus
