### ISSUE TITLE
Incompatible with Aether mod 1.19.2: looks like a bug in some chunks

### ISSUE THREAD

**Issue by LrbsX** [Asek3/Rubidium#468]
When installed together with aether mod in 1.19.2, there will be a bug, see the picture for details.
aether:https://github.com/Gilded-Games/The-Aether/releases/tag/1.19.2-0.2.0

![2023-04-17_22 52 39](https://user-images.githubusercontent.com/95033532/232523975-df2403c8-8606-44cc-833a-b4ba1d05791b.png)
![2023-04-17_22 52 59](https://user-images.githubusercontent.com/95033532/232524074-7aff04cf-1b7b-42c6-be84-ed8b09210c64.png)

[17.4.2023 22:51:28.939] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Lrbs_SCCN, --version, 1.19.2-Forge_43.2.6, --gameDir, D:\Minecraft\1.19.2 Spec, --assetsDir, D:\Minecraft\1.19.2 Spec\assets, --assetIndex, 1.19, --uuid, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 1278, --height, 681, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.6, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[17.4.2023 22:51:28.939] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.5 by Eclipse Adoptium; OS Windows 10 arch amd64 version 10.0
[17.4.2023 22:51:29.191] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/Minecraft/1.19.2%20Spec/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23140!/ Service=ModLauncher Env=CLIENT
[17.4.2023 22:51:29.505] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\Minecraft\1.19.2 Spec\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.6\fmlcore-1.19.2-43.2.6.jar is missing mods.toml file
[17.4.2023 22:51:29.505] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\Minecraft\1.19.2 Spec\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.6\javafmllanguage-1.19.2-43.2.6.jar is missing mods.toml file
[17.4.2023 22:51:29.505] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\Minecraft\1.19.2 Spec\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.6\lowcodelanguage-1.19.2-43.2.6.jar is missing mods.toml file
[17.4.2023 22:51:29.520] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\Minecraft\1.19.2 Spec\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.6\mclanguage-1.19.2-43.2.6.jar is missing mods.toml file
[17.4.2023 22:51:29.599] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[17.4.2023 22:51:30.758] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[17.4.2023 22:51:30.774] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2-Forge_43.2.6, --gameDir, D:\Minecraft\1.19.2 Spec, --assetsDir, D:\Minecraft\1.19.2 Spec\assets, --uuid, --username, Lrbs_SCCN, --assetIndex, 1.19, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 1278, --height, 681]
[17.4.2023 22:51:30.886] [main/INFO] [Rubidium/]: Loaded configuration file for Rubidium: 30 options available, 0 override(s) found
[17.4.2023 22:51:36.204] [pool-3-thread-1/INFO] [net.minecraft.util.datafix.DataFixers/]: Building unoptimized datafixer
[17.4.2023 22:51:38.439] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/D:/Minecraft/1.19.2%20Spec/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23151!/assets/.mcassetsroot' uses unexpected schema
[17.4.2023 22:51:38.440] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/D:/Minecraft/1.19.2%20Spec/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23151!/data/.mcassetsroot' uses unexpected schema
[17.4.2023 22:51:38.454] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17.4.2023 22:51:39.698] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Lrbs_SCCN
[17.4.2023 22:51:39.819] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.1 build 7
[17.4.2023 22:51:40.764] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 43.2.6, for MC 1.19.2 with MCP 20220805.130853
[17.4.2023 22:51:40.765] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v43.2.6 Initialized
[17.4.2023 22:51:42.791] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[17.4.2023 22:51:42.811] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources, Minecraft-Mod-Language-Package-1.18, Minecraft-Mod-Language-Package-1.19, Fix and extra, Misans font
[17.4.2023 22:51:43.017] [Worker-Main-11/WARN] [net.minecraft.server.packs.FolderPackResources/]: Invalid path in datapack: minecraft:font/MiSans_Medium.ttf, ignoring
[17.4.2023 22:51:43.170] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[17.4.2023 22:51:43.333] [Worker-Main-11/WARN] [net.minecraft.client.gui.font.FontManager/]: Unable to load font 'minecraft:default' in fonts.json in resourcepack: 'Misans font'
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:MiSans_Medium.ttf
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at net.minecraft.client.gui.font.providers.TrueTypeGlyphProviderBuilder.m_95499_(TrueTypeGlyphProviderBuilder.java:70) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at net.minecraft.client.gui.font.providers.GlyphProviderBuilderType.m_95413_(GlyphProviderBuilderType.java:41) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at net.minecraft.client.gui.font.FontManager$1.m_5944_(FontManager.java:77) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at net.minecraft.client.gui.font.FontManager$1.m_5944_(FontManager.java:46) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23151!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[17.4.2023 22:51:44.822] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: OUTDATED Current: 43.2.6 Target: 43.2.8
[17.4.2023 22:51:47.036] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:item.goat_horn.play
[17.4.2023 22:51:47.037] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[17.4.2023 22:51:47.277] [Render thread/INFO] [com.mojang.blaze3d.audio.Library/]: OpenAL initialized on device OpenAL Soft on 扬声器 (Realtek(R) Audio)
[17.4.2023 22:51:47.279] [Render thread/INFO] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Sound engine started
[17.4.2023 22:51:47.489] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[17.4.2023 22:51:47.502] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[17.4.2023 22:51:47.505] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17.4.2023 22:51:47.505] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17.4.2023 22:51:47.508] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17.4.2023 22:51:47.508] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17.4.2023 22:51:47.509] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17.4.2023 22:51:48.401] [Render thread/WARN] [net.minecraft.client.renderer.ShaderInstance/]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[17.4.2023 22:51:48.516] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17.4.2023 22:51:48.519] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17.4.2023 22:51:48.519] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17.4.2023 22:52:01.172] [Render thread/WARN] [net.minecraftforge.common.ForgeHooks/WP]: The following mods have version differences that were not resolved:
modernui (version 3.6.3.117 -> MISSING)
oculus (version 1.2.8a -> MISSING)
Things may not work well.
[17.4.2023 22:52:01.775] [Render thread/WARN] [net.minecraft.server.MinecraftServer/]: Missing data pack mod:modernui
[17.4.2023 22:52:01.775] [Render thread/WARN] [net.minecraft.server.MinecraftServer/]: Missing data pack mod:oculus
[17.4.2023 22:52:03.378] [Render thread/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Loaded 17 recipes
[17.4.2023 22:52:03.826] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1484 advancements
[17.4.2023 22:52:06.246] [Render thread/WARN] [net.minecraftforge.common.ForgeHooks/WP]: The following mods have version differences that were not resolved:
modernui (version 3.6.3.117 -> MISSING)
oculus (version 1.2.8a -> MISSING)
Things may not work well.
[17.4.2023 22:52:06.747] [Render thread/WARN] [net.minecraft.server.MinecraftServer/]: Missing data pack mod:modernui
[17.4.2023 22:52:06.747] [Render thread/WARN] [net.minecraft.server.MinecraftServer/]: Missing data pack mod:oculus
[17.4.2023 22:52:07.528] [Render thread/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Loaded 17 recipes
[17.4.2023 22:52:07.713] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1484 advancements
[17.4.2023 22:52:08.242] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Starting integrated minecraft server version 1.19.2
[17.4.2023 22:52:08.243] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Generating keypair
[17.4.2023 22:52:08.324] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file D:\Minecraft\1.19.2 Spec\saves\feedback\serverconfig\curios-server.toml is not correct. Correcting
[17.4.2023 22:52:08.325] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key curiosSettings was corrected from null to its default, []. 
[17.4.2023 22:52:08.635] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[17.4.2023 22:52:11.623] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[17.4.2023 22:52:11.623] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[17.4.2023 22:52:11.623] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[17.4.2023 22:52:11.624] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[17.4.2023 22:52:11.624] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[17.4.2023 22:52:11.624] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[17.4.2023 22:52:11.644] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[17.4.2023 22:52:12.142] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 34%
[17.4.2023 22:52:12.597] [Server thread/INFO] [net.minecraftforge.server.permission.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
[17.4.2023 22:52:12.610] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Time elapsed: 3969 ms
[17.4.2023 22:52:12.734] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing view distance to 8, from 10
[17.4.2023 22:52:12.737] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing simulation distance to 12, from 0
[17.4.2023 22:52:12.858] [Render thread/WARN] [io.netty.util.internal.SystemPropertyUtil/]: Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false
[17.4.2023 22:52:13.345] [Netty Local Client IO #0/INFO] [net.minecraftforge.network.NetworkHooks/]: Connected to a modded server.
[17.4.2023 22:52:13.400] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@2de66769
[17.4.2023 22:52:13.419] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: Lrbs_SCCN[local:E:1fb249bb] logged in with entity id 268 at (-108.94860158836481, 64.0, -132.32041838028724)
[17.4.2023 22:52:13.496] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Lrbs_SCCN joined the game
[17.4.2023 22:52:13.930] [Render thread/INFO] [ChunkBuilder/]: Started 6 worker threads
[17.4.2023 22:52:14.447] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 0 advancements
[17.4.2023 22:52:23.811] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Saving and pausing game...
[17.4.2023 22:52:23.824] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:overworld
[17.4.2023 22:52:23.849] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:the_nether
[17.4.2023 22:52:23.850] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/aether:the_aether
[17.4.2023 22:52:23.852] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:the_end
[17.4.2023 22:52:30.020] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[17.4.2023 22:52:30.025] [Render thread/INFO] [ChunkBuilder/]: Started 6 worker threads
[17.4.2023 22:52:30.045] [Render thread/INFO] [Rubidium/]: Flushed changes to Minecraft configuration
[17.4.2023 22:52:30.754] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing view distance to 14, from 8
[17.4.2023 22:52:30.794] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[17.4.2023 22:52:30.798] [Render thread/INFO] [ChunkBuilder/]: Started 6 worker threads
[17.4.2023 22:52:39.670] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Saved screenshot as 2023-04-17_22.52.39.png
[17.4.2023 22:52:47.535] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] [Debug]: Advanced tooltips: hidden
[17.4.2023 22:52:49.478] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] [Debug]: Advanced tooltips: shown
[17.4.2023 22:52:51.847] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] [Debug]: Chunk borders: shown
[17.4.2023 22:52:59.836] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Saved screenshot as 2023-04-17_22.52.59.png
[17.4.2023 22:53:08.781] [Render thread/WARN] [me.jellysquid.mods.sodium.client.util.NativeBuffer/]: Reclaimed 2172 bytes at address 3019587201024 that were leaked from an unknown location (logging is disabled)
[17.4.2023 22:53:08.782] [Render thread/WARN] [me.jellysquid.mods.sodium.client.util.NativeBuffer/]: Reclaimed 6744 bytes at address 3019479536640 that were leaked from an unknown location (logging is disabled)
[17.4.2023 22:53:08.782] [Render thread/WARN] [me.jellysquid.mods.sodium.client.util.NativeBuffer/]: Reclaimed 8480 bytes at address 3019495647232 that were leaked from an unknown location (logging is disabled)
[17.4.2023 22:53:08.782] [Render thread/WARN] [me.jellysquid.mods.sodium.client.util.NativeBuffer/]: Reclaimed 44960 bytes at address 3019575723264 that were leaked from an unknown location (logging is disabled)
[17.4.2023 22:53:11.748] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Saving and pausing game...
[17.4.2023 22:53:11.754] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:overworld
[17.4.2023 22:53:11.770] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:the_nether
[17.4.2023 22:53:11.772] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/aether:the_aether
[17.4.2023 22:53:11.774] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:the_end
[17.4.2023 22:53:12.424] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Lrbs_SCCN lost connection: Disconnected
[17.4.2023 22:53:12.424] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Lrbs_SCCN left the game
[17.4.2023 22:53:12.473] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Stopping singleplayer server as player logged out
[17.4.2023 22:53:12.489] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[17.4.2023 22:53:12.489] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[17.4.2023 22:53:12.489] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[17.4.2023 22:53:14.297] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:overworld
[17.4.2023 22:53:14.696] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:the_nether
[17.4.2023 22:53:14.697] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/aether:the_aether
[17.4.2023 22:53:14.698] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[feedback]'/minecraft:the_end
[17.4.2023 22:53:14.714] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (feedback): All chunks are saved
[17.4.2023 22:53:14.714] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17.4.2023 22:53:14.714] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (the_aether): All chunks are saved
[17.4.2023 22:53:14.714] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17.4.2023 22:53:14.714] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[17.4.2023 22:53:15.340] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[17.4.2023 22:53:21.002] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

**Comment by Mythx-is-Dead** [comment]
fyi to anyone has gets this, turn biomeblend to 0

**Comment by LrbsX** [comment]
0.6.2b has fixed
