### ISSUE TITLE
Minecraft crashing after starting (1.19.4)

### ISSUE THREAD

**Issue by 0385mrcoolman** [Asek3/Rubidium#506]
The game crashes after starting. I am on Minecraft 1.19.4, Rubidium 0.6.4, Forge 45.0.59. Can someone help me figure out how to fix it?

Full crash report:

java.lang.IllegalAccessError: class me.jellysquid.mods.sodium.client.render.vertex.transform.CommonVertexElement tried to access private field com.mojang.blaze3d.vertex.VertexFormat.f_86013_ (me.jellysquid.mods.sodium.client.render.vertex.transform.CommonVertexElement is in module rubidium@0.6.4 of loader 'TRANSFORMER' @2c0c4c0a; com.mojang.blaze3d.vertex.VertexFormat is in module minecraft@1.19.4 of loader 'TRANSFORMER' @2c0c4c0a)
	at me.jellysquid.mods.sodium.client.render.vertex.transform.CommonVertexElement.getOffsets(CommonVertexElement.java:53) ~[rubidium-0.6.4.jar%23349!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.vertex.VertexFormatDescription.<init>(VertexFormatDescription.java:29) ~[rubidium-0.6.4.jar%23349!/:?] {re:mixin,re:classloading}
	at me.jellysquid.mods.sodium.client.render.vertex.VertexFormatRegistry.get(VertexFormatRegistry.java:14) ~[rubidium-0.6.4.jar%23349!/:?] {re:mixin,re:classloading}
	at com.mojang.blaze3d.vertex.BufferBuilder.handler$zzj000$onFormatChanged(BufferBuilder.java:587) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.pipeline.vertex.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_sort.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_85704_(BufferBuilder.java:128) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.pipeline.vertex.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_sort.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_166779_(BufferBuilder.java:113) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.pipeline.vertex.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_sort.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_234259_(LevelRenderer.java:611) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.clouds.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.sky.MixinWorldRenderer,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:ParrotMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:particle.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sky.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sun_moon.MixinWorldRenderer,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:freecam.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:stars.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109837_(LevelRenderer.java:603) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.clouds.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.sky.MixinWorldRenderer,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:ParrotMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:particle.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sky.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sun_moon.MixinWorldRenderer,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:freecam.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:stars.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.<init>(LevelRenderer.java:262) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.clouds.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.sky.MixinWorldRenderer,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:ParrotMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:particle.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sky.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sun_moon.MixinWorldRenderer,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:freecam.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:stars.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:516) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:freecam.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[forge-45.0.59.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.59.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.vertex.transform.CommonVertexElement.getOffsets(CommonVertexElement.java:53) ~[rubidium-0.6.4.jar%23349!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.vertex.VertexFormatDescription.<init>(VertexFormatDescription.java:29) ~[rubidium-0.6.4.jar%23349!/:?] {re:mixin,re:classloading}
	at me.jellysquid.mods.sodium.client.render.vertex.VertexFormatRegistry.get(VertexFormatRegistry.java:14) ~[rubidium-0.6.4.jar%23349!/:?] {re:mixin,re:classloading}
	at com.mojang.blaze3d.vertex.BufferBuilder.handler$zzj000$onFormatChanged(BufferBuilder.java:587) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.pipeline.vertex.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_sort.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_85704_(BufferBuilder.java:128) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.pipeline.vertex.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_sort.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_166779_(BufferBuilder.java:113) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.pipeline.vertex.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_sort.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_234259_(LevelRenderer.java:611) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.clouds.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.sky.MixinWorldRenderer,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:ParrotMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:particle.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sky.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sun_moon.MixinWorldRenderer,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:freecam.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:stars.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109837_(LevelRenderer.java:603) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.clouds.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.sky.MixinWorldRenderer,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:ParrotMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:particle.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sky.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sun_moon.MixinWorldRenderer,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:freecam.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:stars.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.<init>(LevelRenderer.java:262) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.clouds.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:rubidium.mixins.json:features.sky.MixinWorldRenderer,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:ParrotMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:betterfpsdist.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:particle.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sky.MixinWorldRenderer,pl:mixin:APP:sodium-extra.mixins.json:sun_moon.MixinWorldRenderer,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin,pl:mixin:APP:freecam.mixins.json:LevelRendererMixin,pl:mixin:APP:sodium-extra.mixins.json:stars.MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:516) ~[client-1.19.4-20230314.122934-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:freecam.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by mosharky** [comment]
I'm getting this exact same crash but on 1.20

**Comment by mosharky** [comment]
Disabling [Better Ping Display](https://www.curseforge.com/minecraft/mc-mods/better-ping-display) worked for me 🤦‍♂️

**Comment by ghost** [comment]
Same crash here on 1.19.4, using the same versions as you. I could have sworn my indev pack was working yesterday, and I don't believe I updated or added any mods.

**Comment by mosharky** [comment]
ok so i actually did figure it out; Rubidium "crashes" when there's other errors on startup. If you have a mod loading error for example, it'll show you this error instead of the mod loading error, so just disable Rubidium and figure out what your error is.

I could be wrong, but this is what I observed

**Comment by ghost** [comment]
Ah, thanks. Sure enough, it was related to something else.

**Comment by EATERYRED** [comment]
Me too, When I Want to load my mod in MCreator my minecraft java is crashing after startup but when the startup goes away in less than a second there a a strang message writing: [][][][][][][][][], Then it Crashes, That was Creepy For the First Time!

**Comment by Asek3** [comment]
Unrelated to Rubidium
