### ISSUE TITLE
Sometimes crashes on startup, blaming Immersive Engineering

### ISSUE THREAD

**Issue by aaronhowser1** [Asek3/Rubidium#536]
Crash Report: https://gist.github.com/aaronhowser1/9038c8e3a122b433ea4fae9eeb298ceb
latest.log: https://gist.github.com/aaronhowser1/8a6d4d61f437c5be0d0d219403ac724f

rubidium-0.6.2b
rubidium_extras-1.19.2_v1.4.3
ImmersiveEngineering-1.19.2-9.2.2-165

Doesn't happen every time, doesn't even happen often. I just got this for the first time, and it didn't happen the next launch.

**Comment by SiverDX** [comment]
this is on immersive engineering, why post this here

**Comment by aaronhowser1** [comment]
It's a game rendering thing, and the crash report mentions Rubidium, so I assumed 🤷‍♂️

I can move it there if this is the wrong place for it

**Comment by SiverDX** [comment]
it's not a rendering thing

Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
	at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.computeLaunchPluginTransformerSet(LaunchPluginHandler.java:68) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:64) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.ModLauncherFactory.createWrapper(ModLauncherFactory.java:15) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.ClassLoaderFactory.create(ClassLoaderFactory.java:25) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:37) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:267) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:163) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$6(EventBus.java:106) ~[eventbus-6.0.3.jar%23134!/:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:106) ~[eventbus-6.0.3.jar%23134!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:102) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.3.jar%23134!/:?]
	at blusunrize.immersiveengineering.client.ClientProxy.initWithMC(ClientProxy.java:167) ~[ImmersiveEngineering-1.19.2-9.2.2-165.jar%23528!/:?]
	at blusunrize.immersiveengineering.client.ClientProxy.modConstruction(ClientProxy.java:158) ~[ImmersiveEngineering-1.19.2-9.2.2-165.jar%23528!/:?]
	at net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:123) ~[fmlcore-1.19.2-43.2.14.jar%23664!/:?]
	at blusunrize.immersiveengineering.ImmersiveEngineering.<init>(ImmersiveEngineering.java:136) ~[ImmersiveEngineering-1.19.2-9.2.2-165.jar%23528!/:?]
	... 14 more

**Comment by Asek3** [comment]
Unrelated to Rubidium absolutely, report to IE
