### ISSUE TITLE
[1.16.5 & 1.18.2] Error when rendering multiblocks in patchouli guide

### ISSUE THREAD

**Issue by HydrogenC** [Asek3/Rubidium#55]
Multiblocks in the patchouli guide (e.g. Botania guide) cannot be rendered. The log reads: 
```
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:0, y:0, z:0
  Block Class:   class it.zerono.mods.zerocore.lib.block.multiblock.MultiblockPartBlock
  Registry Name: bigreactors:basic_reactorcasing
  State:         Block{bigreactors:basic_reactorcasing}
 Tile at position
  Tile Class:    class it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.part.ReactorCasingEntity
  Tile Id:       bigreactors:reactorcasing
  Tile NBT:      {zcvase_payload:{},zcvase_version:-1,x:0,y:0,z:0,id:"bigreactors:reactorcasing"}
This functionality can be disabled in the CCL config file.
You can also turn off player messages in the CCL config file.

net.minecraft.crash.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:68) ~[?:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderModel(CCBlockRendererDispatcher.java:72) ~[codechickenlib:1.16.5-4.0.7.445]
	at it.zerono.mods.zerocore.lib.compat.patchouli.component.standardpage.Multiblock.doWorldRenderPass(Multiblock.java:215) ~[zerocore:1.16.5-2.1.9]
	at it.zerono.mods.zerocore.lib.compat.patchouli.component.standardpage.Multiblock.renderElements(Multiblock.java:192) ~[zerocore:1.16.5-2.1.9]
	at it.zerono.mods.zerocore.lib.compat.patchouli.component.standardpage.Multiblock.renderMultiblock(Multiblock.java:181) ~[zerocore:1.16.5-2.1.9]
	at it.zerono.mods.zerocore.lib.compat.patchouli.component.standardpage.Multiblock.renderPage(Multiblock.java:126) ~[zerocore:1.16.5-2.1.9]
	at it.zerono.mods.zerocore.lib.compat.patchouli.component.standardpage.AbstractStandardPageComponent.render(AbstractStandardPageComponent.java:67) ~[zerocore:1.16.5-2.1.9]
	at vazkii.patchouli.client.book.template.BookTemplate.lambda$render$3(BookTemplate.java:141) ~[patchouli:1.16.4-53.2]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at vazkii.patchouli.client.book.template.BookTemplate.render(BookTemplate.java:139) ~[patchouli:1.16.4-53.2]
	at vazkii.patchouli.client.book.page.PageTemplate.render(PageTemplate.java:36) ~[patchouli:1.16.4-53.2]
	at vazkii.patchouli.client.book.gui.GuiBookEntry.drawPage(GuiBookEntry.java:115) ~[patchouli:1.16.4-53.2]
	at vazkii.patchouli.client.book.gui.GuiBookEntry.drawForegroundElements(GuiBookEntry.java:94) ~[patchouli:1.16.4-53.2]
	at vazkii.patchouli.client.book.gui.GuiBook.drawScreenAfterScale(GuiBook.java:133) ~[patchouli:1.16.4-53.2]
	at vazkii.patchouli.client.book.gui.GuiBook.func_230430_a_(GuiBook.java:121) ~[patchouli:1.16.4-53.2]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:377) ~[forge:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:370) ~[forge:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.33.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 6
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:152) ~[forge:?]
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66) ~[forge:?]
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:110) ~[forge:?]
	at net.minecraft.client.renderer.model.BakedQuad.pipe(BakedQuad.java:42) ~[?:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:122) ~[forge:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:85) ~[forge:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51) ~[?:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:63) ~[?:?]
	... 30 more
```
It also happens without CCL, but just renders nothing without output. 
If this cannot be solved thoroughly, is there any way to fix this via disabling a mixin?

**Comment by ToxicFrog** [comment]
I was seeing this as well on 1.18.1, and actually came here to file a bug about it, but found out that after uninstalling Radium the multiblock machines in patchouli books are displaying fine. So if you're running both Radium and Rubidium, see if disabling Radium fixes it? If disabling either one fixes it, maybe it's a bad interaction between the two, not a bug isolated to one or the other.

**Comment by HydrogenC** [comment]
> I was seeing this as well on 1.18.1, and actually came here to file a bug about it, but found out that after uninstalling Radium the multiblock machines in patchouli books are displaying fine. So if you're running both Radium and Rubidium, see if disabling Radium fixes it? If disabling either one fixes it, maybe it's a bad interaction between the two, not a bug isolated to one or the other.

Thank you, that works for 1.18.2. I suppose that this could be achieved by disabling Radium mixin instead of removing the entire mod.

**Comment by HydrogenC** [comment]
> Maybe part of the `shapes` mixin? I don't have the wherewithal to look into it right now, but please report back if you do.

It is mixin.shapes.shape_merging

**Comment by Asek3** [comment]
Related to Radium, transferring issue
