### ISSUE TITLE
Crash when rendering lava

### ISSUE THREAD

**Issue by twothe** [Asek3/Rubidium#632]
When rendering lava of level=0 the renderer crashes:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23385!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23385!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23385!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23385!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23385!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```

Crash Log: 
[crash-2023-09-28_23.40.21-client.txt](https://github.com/Asek3/Rubidium/files/12754164/crash-2023-09-28_23.40.21-client.txt)

The issue appears every time and instantly crashes the game when such a block is appearing.

**Comment by twothe** [comment]
Also seems to happen with other lava levels.
[crash-2023-09-29_00.11.02-client.txt](https://github.com/Asek3/Rubidium/files/12754284/crash-2023-09-29_00.11.02-client.txt)

**Comment by GodzillaWithTheMicrowave44** [comment]
Seems to be an issue with lava next to transparent blocks like leaves or glass.

**Comment by Esseit** [comment]
It is, and according to issue #629, there is a fix in this posted in the rubidium upstream. Hopefully once that version is released this problem will no longer be an issue

**Comment by zLudociel** [comment]
this is still an issue for me

**Comment by justGyga** [comment]
Have the same problem

**Comment by lvinyl** [comment]
its still hapenning
