### ISSUE TITLE
Minecraft Crash Report  1.20.1

### ISSUE THREAD

**Issue by SkrimanS** [Asek3/Rubidium#638]
Not sure if the problem is just rubidium. Perhaps you can help me

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-10-01 22:45:58
Description: Encountered exception while building chunk meshes

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
-- Block being rendered --
Details:
	Block: Block{minecraft:lava}[level=8]
	Block location: World: (-2187,77,-4993), Section: (at 5,13,15 in -137,4,-313; chunk contains blocks -2192,-64,-5008 to -2177,319,-4993), Region: (-5,-10; contains chunks -160,-320 to -129,-289, blocks -2560,-64,-5120 to -2049,319,-4609)
	Chunk section: RenderSection at chunk (-137, 4, -313) from (-2192, 64, -5008) to (-2177, 79, -4993)
	Render context volume: BoundingBox{minX=-2194, minY=62, minZ=-5010, maxX=-2175, maxY=81, maxZ=-4991}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23354!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by Chickne** [comment]
The problem currently is Rubidium, sadly. There's a glitch currently where it cannot render lava blocks interacting with clear blocks such as grass. The next update already has it fixed, we now just have to wait for it to release.

**Comment by GeggsLegs** [comment]
Any idea when this update might happen? kind of unusable as it soft-locks a world after a bit

**Comment by Chickne** [comment]
[rubidium-0.7.1a.zip](https://github.com/Asek3/Rubidium/files/12839002/rubidium-0.7.1a.zip)

Here's a unofficial fix made on the discord for the mod. There are still a few issues like Oculus being unusable and other minor things but the game should be playable.

**Comment by FastBoye127** [comment]
That fix worked for me! Thanks!
