### ISSUE TITLE
CRASH [1.20.1]

### ISSUE THREAD

**Issue by idkwhoisit** [Asek3/Rubidium#642]
crashed...

1)Ran around the world

2)idk, probably new chanks were loading

3)Game Crashes

4)when you enter the world again, it crashes after a couple of seconds

mods: 
rubidium [lastet vesion]
oculus (without oculus same crash) [lastet version]

info:
minecraft 1.20.1
forge 47.2.1
gtx 1050ti
32gb ram 
win 11
java 8 

Fix it please

[crash-2023-10-08_20.18.12-client.txt](https://github.com/Asek3/Rubidium/files/12841263/crash-2023-10-08_20.18.12-client.txt)

**Comment by KittyluvzCow** [comment]
https://github.com/Asek3/Rubidium/issues/644
Read my comment on this form. Downgrade Xaero's World Map and it should fix the problem

**Comment by DrMjonter** [comment]
Same issue here, found it related to lava blocks being adjacent to a transparent block - found a homebrew 0.7.1a version someone posted and that works for me
[mod.zip](https://github.com/Asek3/Rubidium/files/12873920/mod.zip)

**Comment by MROGAMES** [comment]
Same thing is happening to me.

**Comment by VoidLifter** [comment]
I also have this isue

**Comment by Flintley** [comment]
same

**Comment by AlexDerProGamer** [comment]
> Same issue here, found it related to lava blocks being adjacent to a transparent block - found a homebrew 0.7.1a version someone posted and that works for me [mod.zip](https://github.com/Asek3/Rubidium/files/12873920/mod.zip)

Source link?

**Comment by scytail** [comment]
Also having this problem

**Comment by Ritticle** [comment]
> Same issue here, found it related to lava blocks being adjacent to a transparent block - found a homebrew 0.7.1a version someone posted and that works for me [mod.zip](https://github.com/Asek3/Rubidium/files/12873920/mod.zip)

This helped me with my issue. Thanks for the save!

**Comment by ron4821** [comment]
Getting the same error.

`[20:00:28] [Chunk Render Task Executor #3/ERROR]: Chunk build failed
net.minecraft.ReportedException: Encountered exception while building chunk meshes
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) [rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) [rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	... 4 more`

**Comment by ron4821** [comment]
> Same issue here, found it related to lava blocks being adjacent to a transparent block - found a homebrew 0.7.1a version someone posted and that works for me [mod.zip](https://github.com/Asek3/Rubidium/files/12873920/mod.zip)

Works for me too! Thanks :)

**Comment by bkoee** [comment]
Any official fix? I don't really want a homebrew fix, would rather deal with the devs directly bc what if there is a problem with the homebrew?

**Comment by Coffeline** [comment]
I had the same issue. Every time I approached a ruined nether portal the game would crash. The homebrew version fixed it for me, I even tested in creative with mods like framed blocks and such.
A good workaround for now!

**Comment by Port06** [comment]
For those who don't know: The unoficial version that works was released the day the previous update dropped but he still hasn't made an official release for it

**Comment by clarence112** [comment]
Unofficial fix doesn't seem to work for me, specifically when the lava is next to leaves
