### ISSUE TITLE
Random Crash But Same Error

### ISSUE THREAD

**Issue by shinoharatsuru** [Asek3/Rubidium#653]
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-10-18 22:58:35
Description: Encountered exception while building chunk meshes

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
-- Block being rendered --
Details:
	Block: Block{minecraft:lava}[level=4]
	Block location: World: (563,120,-97), Section: (at 3,8,15 in 35,7,-7; chunk contains blocks 560,-64,-112 to 575,319,-97), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Chunk section: RenderSection at chunk (35, 7, -7) from (560, 112, -112) to (575, 127, -97)
	Render context volume: BoundingBox{minX=558, minY=110, minZ=-114, maxX=577, maxY=129, maxZ=-95}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23297!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Takoyaki0825'/116, l='ClientLevel', x=488.99, y=20.14, z=-36.10]]
	Chunk stats: 1024, 598
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,135,0), Section: (at 0,7,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 59807 game time, 59807 day time
	Server brand: forge
	Server type: Integrated singleplayer server

**Comment by rrusciguy** [comment]
I am receiving this same error, seems to happen when generating new chunks but doesn't happen consistently
MC: 1.20.1
Neoforge 41.7.79
Rubidium 0.7.1
magnesium/rubidium extras  1.4.3
do not have oculus or any shaders installed

**Comment by Bob74** [comment]
Duplicate with https://github.com/Asek3/Rubidium/issues/642 (an unofficial fixed jar is provided in the thread)
