### ISSUE TITLE
everytime i open the "video settings" i crash i dont know why.

### ISSUE THREAD

**Issue by MunzL** [Asek3/Rubidium#657]
here is the crash report. ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/19/23 7:18 PM
Description: mouseClicked event handler

java.lang.NoSuchMethodError: me.jellysquid.mods.sodium.client.gui.options.control.CyclingControl.<init>(Lme/jellysquid/mods/sodium/client/gui/options/Option;Ljava/lang/Class;[Ljava/lang/String;)V
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.md1ba0f2$lambda$InjectGeneral$0$2(SodiumGameOptionPages.java:555) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.SodiumGameOptionsMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages$$Lambda$4409/1692369954.apply(Unknown Source) ~[?:?] {}
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.<init>(OptionImpl.java:49) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:reeses_sodium_options.mixins.json:sodium.MixinOptionImpl,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.<init>(OptionImpl.java:17) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:reeses_sodium_options.mixins.json:sodium.MixinOptionImpl,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl$Builder.build(OptionImpl.java:214) ~[?:?] {re:mixin,re:classloading}
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.handler$zek000$InjectGeneral(SodiumGameOptionPages.java:576) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.SodiumGameOptionsMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.general(SodiumGameOptionPages.java:131) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.SodiumGameOptionsMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:54) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dynamiclightsreforged.mixins.json:sodium.SodiumSettingsMixin,pl:mixin:APP:reeses_sodium_options.mixins.json:sodium.MixinSodiumOptionsGUI,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.SodiumSettingsMixin,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.ZoomSettingsPage,pl:mixin:A}
	at net.minecraft.client.gui.screen.OptionsScreen.handler$zcl000$open(OptionsScreen.java:523) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.options.MixinOptionsScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.OptionsScreen.func_213059_g(OptionsScreen.java) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.options.MixinOptionsScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.OptionsScreen$$Lambda$4375/585785425.onPress(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4347/1319869164.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:mixin,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4346/1322358080.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3743/2004981696.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:306) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.MixinWindow,pl:mixin:APP:magnesium_extras.mixins.json:BorderlessFullscreen.MainWindowAccessor,pl:mixin:APP:magnesium_extras.mixins.json:BorderlessFullscreen.WindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/297031141.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.md1ba0f2$lambda$InjectGeneral$0$2(SodiumGameOptionPages.java:555) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.SodiumGameOptionsMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages$$Lambda$4409/1692369954.apply(Unknown Source) ~[?:?] {}
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.<init>(OptionImpl.java:49) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:reeses_sodium_options.mixins.json:sodium.MixinOptionImpl,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.<init>(OptionImpl.java:17) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:reeses_sodium_options.mixins.json:sodium.MixinOptionImpl,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl$Builder.build(OptionImpl.java:214) ~[?:?] {re:mixin,re:classloading}
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.handler$zek000$InjectGeneral(SodiumGameOptionPages.java:576) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.SodiumGameOptionsMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.general(SodiumGameOptionPages.java:131) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.SodiumGameOptionsMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:54) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dynamiclightsreforged.mixins.json:sodium.SodiumSettingsMixin,pl:mixin:APP:reeses_sodium_options.mixins.json:sodium.MixinSodiumOptionsGUI,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.SodiumSettingsMixin,pl:mixin:APP:magnesium_extras.mixins.json:SodiumConfig.ZoomSettingsPage,pl:mixin:A}
	at net.minecraft.client.gui.screen.OptionsScreen.handler$zcl000$open(OptionsScreen.java:523) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.options.MixinOptionsScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.OptionsScreen.func_213059_g(OptionsScreen.java) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.options.MixinOptionsScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.OptionsScreen$$Lambda$4375/585785425.onPress(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4347/1319869164.run(Unknown Source) ~[?:?] {}
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.OptionsScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:classloading,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A,re:mixin,xf:fml:configured:set_background_texture_2,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4346/1322358080.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3743/2004981696.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:306) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.MixinWindow,pl:mixin:APP:magnesium_extras.mixins.json:BorderlessFullscreen.MainWindowAccessor,pl:mixin:APP:magnesium_extras.mixins.json:BorderlessFullscreen.WindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/297031141.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1113082848 bytes (1061 MB) / 2286944256 bytes (2181 MB) up to 5339348992 bytes (5092 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5728m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		smoothchunk1.16.5-2.0.jar                         |Smoothchunk mod               |smoothchunk                   |2.0                 |DONE      |Manifest: NOSIGNATURE
		saturn-mc1.16.5-0.0.3.jar                         |Saturn                        |saturn                        |0.0.3               |DONE      |Manifest: NOSIGNATURE
		dynamiclightsreforged-mc1.16.5_v1.0.1.jar         |Dynamic Lights Reforged       |dynamiclightsreforged         |mc1.16.5_v1.0.1     |DONE      |Manifest: NOSIGNATURE
		EntityCulling-1.16.5-2.1.7.jar                    |Entity Culling                |entity_culling                |2.1.7               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.8.0.1009.jar                         |Just Enough Items             |jei                           |7.8.0.1009          |DONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		Ksyxis-Forge1.14thru1.16-1.1.jar                  |Ksyxis                        |ksyxis                        |1.1                 |DONE      |Manifest: NOSIGNATURE
		TextruesRubidiumOptions-1.0.8-mc1.16.5.jar        |TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.8-mc1.16.5      |DONE      |Manifest: NOSIGNATURE
		spark-1.9.1-forge.jar                             |spark                         |spark                         |1.9.1               |DONE      |Manifest: NOSIGNATURE
		rubidium-mc1.16.5-0.2.13.jar                      |Rubidium                      |rubidium                      |0.2.13              |DONE      |Manifest: NOSIGNATURE
		memorysettings-1.16.5-5.2.jar                     |memorysettings mod            |memorysettings                |1.16.5-5.2          |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.28.jar                               |Clumps                        |clumps                        |6.0.0.28            |DONE      |Manifest: NOSIGNATURE
		kryptonreforged-mc1.16.5_v1.0.0.jar               |Krypton Reforged              |kryptonreforged               |mc1.16.5_v1.0.0     |DONE      |Manifest: NOSIGNATURE
		lootintegrations-1.2.jar                          |Lootintegrations mod          |lootintegrations              |1.2                 |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-4.1m.jar                      |Performant                    |performant                    |3.73m               |DONE      |Manifest: NOSIGNATURE
		configured-1.5.4-1.16.5.jar                       |Configured                    |configured                    |1.5.4               |DONE      |Manifest: NOSIGNATURE
		doespotatotick-1.16.5-3.6.2.jar                   |DoesPotatoTick                |doespotatotick                |1.16.5-3.6.2        |DONE      |Manifest: NOSIGNATURE
		lootr-1.16.5-0.2.18.49.jar                        |Lootr                         |lootr                         |0.1.15.46           |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		dynviewdist-2.0.jar                               |Dynamic view distance         |dynview                       |1.8                 |DONE      |Manifest: NOSIGNATURE
		magnesium_extras-mc1.16.5_v1.4.0.jar              |Magnesium Extras              |magnesium_extras              |mc1.16.5_v1.4.0     |DONE      |Manifest: NOSIGNATURE
		memoryleakfix-forge-pre1.17-1.0.0.jar             |Memory Leak Fix               |memoryleakfix                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.128.jar         |Just Enough Resources         |jeresources                   |0.12.1.128          |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		chunksending-1.16.5-2.5.jar                       |chunksending mod              |chunksending                  |1.16.5-2.5          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 40a9c225-97b9-423a-b635-1b63b8313a17
	Launched Version: forge-36.2.39
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 545.84, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

**Comment by MunzL** [comment]
i uninstalled magnesium and that seemed to fix the issue i dont know why but maybe someone can tell me.

**Comment by amaury-d** [comment]
Duplicate of #654
