### ISSUE TITLE
1.20.1 (Forge: 47.2.1) Crash "Encountered exception while building chunk meshes"

### ISSUE THREAD

**Issue by ArsiTheFox** [Asek3/Rubidium#667]
I am running a modpack and the game keeps crashing and I can't find out what mod is causing it... It works for a while but when I start rendering chunks I crash.
[crash-2023-10-25_01.13.22-client.txt](https://github.com/Asek3/Rubidium/files/13162005/crash-2023-10-25_01.13.22-client.txt)

I looked through the crash report and couldn't find what caused it

**Comment by Kalmorph** [comment]
Getting a similar error:

`[25out.2023 08:43:55.262] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Encountered exception while building chunk meshes
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	... 4 more`

**Comment by Kalmorph** [comment]
Getting a similar error:

`[25out.2023 08:43:55.262] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Encountered exception while building chunk meshes
	at me.jellysquid.mod
[2023-10-25-1.log](https://github.com/Asek3/Rubidium/files/13165598/2023-10-25-1.log)
s.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23269!/:?]
	... 4 more`

[2023-10-25-1.log](https://github.com/Asek3/Rubidium/files/13165613/2023-10-25-1.log)

**Comment by DuisPlay** [comment]
Getting a similar error in combination with Alex's Caves, when i'm in a toxic cave:
net.minecraft.ReportedException: Encountered exception while building chunk meshes
	at TRANSFORMER/rubidium@0.7.1/me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184)
	at TRANSFORMER/rubidium@0.7.1/me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151)
	at TRANSFORMER/rubidium@0.7.1/me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45)
	at TRANSFORMER/rubidium@0.7.1/me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at TRANSFORMER/rubidium@0.7.1/me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at TRANSFORMER/rubidium@0.7.1/me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340)
	at TRANSFORMER/rubidium@0.7.1/me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125)
	... 4 more
[latest.log](https://github.com/Asek3/Rubidium/files/13171935/latest.log)

**Comment by ArsiTheFox** [comment]
Hekk

**Comment by ron4821** [comment]
Getting the exact same issue.

`[20:00:28] [Chunk Render Task Executor #3/ERROR]: Chunk build failed
net.minecraft.ReportedException: Encountered exception while building chunk meshes
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) [rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) [rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23342!/:?]
	... 4 more`

**Comment by Juliandev02** [comment]
Im also getting the same issue. 

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-10-27 20:18:29
Description: Encountered exception while building chunk meshes

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
Mixins in Heaven:
	me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer:
		net.coderbot.iris.compat.sodium.mixin.separate_ao.MixinFluidRenderer (mixins.oculus.compat.sodium.json)
-- Block being rendered --
Details:
	Block: Block{minecraft:lava}[level=8]
	Block location: World: (-204,90,310), Section: (at 4,10,6 in -13,5,19; chunk contains blocks -208,-64,304 to -193,319,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Chunk section: RenderSection at chunk (-13, 5, 19) from (-208, 80, 304) to (-193, 95, 319)
	Render context volume: BoundingBox{minX=-210, minY=78, minZ=302, maxX=-191, maxY=97, maxZ=321}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23234!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

Mixins in Heaven:
	me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask:
		com.jozufozu.flywheel.mixin.sodium.ChunkBuilderMeshingTaskMixin (flywheel.sodium.mixins.json)
		net.coderbot.iris.compat.sodium.mixin.block_id.MixinChunkRenderRebuildTask (mixins.oculus.compat.sodium.json)```

**Comment by Syndaryl** [comment]
Same issue here.

Not sure how many of us are running the Create mod but I'm seeing a fair amount of Flywheel floating around.

Issue happens with or without Iris/Oculus installed.
[debug.log](https://github.com/Asek3/Rubidium/files/13196530/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/13196531/latest.log)
[crash-2023-10-28_14.54.16-client.txt](https://github.com/Asek3/Rubidium/files/13196532/crash-2023-10-28_14.54.16-client.txt)

**Comment by Kalmorph** [comment]
This is exclusively caused by Rubidium.
I'm currently replacing it with [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) and it stopped crashing.

**Comment by pbeczyuk** [comment]
> This is exclusively caused by Rubidium. I'm currently replacing it with [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) and it stopped crashing.

Yyup

**Comment by EvanMcIntyre4377** [comment]
As mentioned above this is caused exclusively by Rubidium, It occurs when Lava is adjacent to a Leaf block (potentially other liquids?). (Can send logs but its basically the same error as above, tested with only Rubidium installed on forge 47.2.0) Thought Id mention since I figured out the issue before the mod causing it.
[crash-2023-11-29_10.51.04-client.txt](https://github.com/Asek3/Rubidium/files/13504483/crash-2023-11-29_10.51.04-client.txt)
