### ISSUE TITLE
Crash when trying to render lava next to leaves 

### ISSUE THREAD

**Issue by Chackr** [Asek3/Rubidium#679]
Game crashes instantly when trying to place lava next to leaves block (any type) or loading a chunk where lava is generated next to leaves block
![Untitled](https://github.com/Asek3/Rubidium/assets/69166682/5bfbf273-6946-4e6a-a652-81158fb3be2c)

Crash report:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-11-03 19:51:24
Description: Encountered exception while building chunk meshes

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
-- Block being rendered --
Details:
	Block: Block{minecraft:lava}[level=0]
	Block location: World: (-1060,80,231), Section: (at 12,0,7 in -67,5,14; chunk contains blocks -1072,-64,224 to -1057,319,239), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,-64,0 to -1025,319,511)
	Chunk section: RenderSection at chunk (-67, 5, 14) from (-1072, 80, 224) to (-1057, 95, 239)
	Render context volume: BoundingBox{minX=-1074, minY=78, minZ=222, maxX=-1055, maxY=97, maxZ=241}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23245!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

**Comment by Chackr** [comment]
Solution found here https://github.com/Asek3/Rubidium/files/12873920/mod.zip
