### ISSUE TITLE
Crash while render

### ISSUE THREAD

**Issue by ScaredFoxJr** [Asek3/Rubidium#683]
[crash-2023-11-06_01.11.08-client.txt](https://github.com/Asek3/Rubidium/files/13260935/crash-2023-11-06_01.11.08-client.txt)

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-11-06 01:11:08
Description: Encountered exception while building chunk meshes

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
-- Block being rendered --
Details:
	Block: Block{minecraft:lava}[level=0]
	Block location: World: (-862,81,77), Section: (at 2,1,13 in -54,5,4; chunk contains blocks -864,0,64 to -849,255,79), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Chunk section: RenderSection at chunk (-54, 5, 4) from (-864, 80, 64) to (-849, 95, 79)
	Render context volume: BoundingBox{minX=-866, minY=78, minZ=62, maxX=-847, maxY=97, maxZ=81}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23163!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['ScaredFoxJunior'/157, l='ClientLevel', x=-608.26, y=133.48, z=-16.65]]
	Chunk stats: 16384, 4241
	Level dimension: minecraft:the_nether
	Level spawn location: World: (32,76,-64), Section: (at 0,12,0 in 2,4,-4; chunk contains blocks 32,0,-64 to 47,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 14085 game time, 14085 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:rubidium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:client.MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:client.MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: mod_resources, vanilla, file/Faithful 32x - 1.20.2

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2362755816 bytes (2253 MiB) / 7348420608 bytes (7008 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25869.67
	Virtual memory used (MB): 22353.40
	Swap memory total (MB): 9544.26
	Swap memory used (MB): 388.11
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Loaded Shaderpack: ComplementaryUnbound_r5.0.1 1.20+
		Profile: HIGH (+0 options changed by user)
	Launched Version: 1.20.1-forge-47.2.0
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/Faithful 32x - 1.20.2 (incompatible)
	Current Language: en_en
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['ScaredFoxJunior'/157, l='ServerLevel[Incen, Oculus, Rubid, Chunk Preg]', x=-607.16, y=133.48, z=-16.63]]
	Data Packs: vanilla, mod:chunkpregen (incompatible), mod:forge, mod:incendium, mod:rubidium, mod:oculus
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Chunk+Pregenerator-1.20-4.2.3.jar                 |Chunk Pregenerator            |chunkpregen                   |1.20-4.2.3          |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Incendium_1.20.1_v5.3.1.jar                       |Incendium                     |incendium                     |5.3.1               |DONE      |Manifest: NOSIGNATURE
		rubidium-mc1.20.1-0.7.1.jar                       |Rubidium                      |rubidium                      |0.7.1               |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.9.jar                         |Oculus                        |oculus                        |1.6.9               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2a9b28a6-7f05-4c17-825a-4c141ea69440
	FML: 47.2
	Forge: net.minecraftforge:47.2.0

**Comment by AngV01** [comment]
me too

**Comment by BeastLe9enD** [comment]
same here 
```
[21:10:10] [Render thread/WARN] [minecraft/SoundEngine]: Unable to play empty soundEvent: minecraft:entity.salmon.ambient
[21:10:14] [Chunk Render Task Executor #1/ERROR] [ChunkBuilder/]: Chunk build failed
net.minecraft.ReportedException: Encountered exception while building chunk meshes
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	... 4 more
Negative index in crash report handler (6/27)
[21:10:15] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[21:10:15] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.ReportedException: Encountered exception while building chunk meshes
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	... 4 more
[21:10:15] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 54685f5f-8545-415a-a757-12e7159a9e09
```

**Comment by AngV01** [comment]
> same here
> 
> ```
> [21:10:10] [Render thread/WARN] [minecraft/SoundEngine]: Unable to play empty soundEvent: minecraft:entity.salmon.ambient
> [21:10:14] [Chunk Render Task Executor #1/ERROR] [ChunkBuilder/]: Chunk build failed
> net.minecraft.ReportedException: Encountered exception while building chunk meshes
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:computing_frames,re:classloading}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:classloading}
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
> 	... 4 more
> Negative index in crash report handler (6/27)
> [21:10:15] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
> [21:10:15] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown!
> net.minecraft.ReportedException: Encountered exception while building chunk meshes
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:184) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:computing_frames,re:classloading}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:classloading}
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23147!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
> 	... 4 more
> [21:10:15] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 54685f5f-8545-415a-a757-12e7159a9e09
> ```

Bro.... Try to use embeddium for this problem

**Comment by AngV01** [comment]
If you are using rubidium 0.7.1 in 1.20.1 (if it happens with other versions, it may also solve it)
use the embeddium mod...

**Comment by L3G1TN00BZ** [comment]
Howdy, this fixed worked for me

https://cdn.discordapp.com/attachments/1147962967560826962/1156184878640025661/rubidium-mc1.20.1-0.7.1a.jar?ex=655c8f13&is=654a1a13&hm=8bd0305d4a9be57614e1dbe7696ffcc03ba0b3e075f554421d7dd2a15729799d&


Sources
@alexgravitos in the Reforged Hub Discord https://discord.gg/uqR3JUMZ

https://github.com/Reforged-Hub/rubidium-upstream/pull/1/files

**Comment by tamanor** [comment]
> Howdy, this fixed worked for me
> 
> https://cdn.discordapp.com/attachments/1147962967560826962/1156184878640025661/rubidium-mc1.20.1-0.7.1a.jar?ex=655c8f13&is=654a1a13&hm=8bd0305d4a9be57614e1dbe7696ffcc03ba0b3e075f554421d7dd2a15729799d&
> 
> Sources @alexgravitos in the Reforged Hub Discord https://discord.gg/uqR3JUMZ
> 
> https://github.com/Reforged-Hub/rubidium-upstream/pull/1/files

I've seen this fix mentioned a few times, is it safe? I might just be overly cautious but with the whole situation that happened with mods some months ago. and would really like use Rubidium on my server
to help my friends on this computer and to get rid of the annoying permanent message in the top left of the screen from oculus ^^ about getting rubidium.

**Comment by L3G1TN00BZ** [comment]
Oh what was the situation with mods? Also he seems trustworthy and ive been using the fix for a while now and it seems good.

**Comment by L3G1TN00BZ** [comment]
![image](https://github.com/Asek3/Rubidium/assets/25547334/b433c75b-b2ab-495d-8e46-ee27eff1866d)

**Comment by tamanor** [comment]
> Oh what was the situation with mods? Also he seems trustworthy and I've been using the fix for a while now and it seems good.

It was back around May/June this year there was a bunch of mods that got infected with a virus on curse and other mod sites, its been delt with now but kind of just makes me weary when downloading from unknown sources ^^. 
I probably would not be as cautious if it was just for me but I would be getting a few others to download it.

**Comment by tamanor** [comment]
> ![image](https://user-images.githubusercontent.com/25547334/283079994-b433c75b-b2ab-495d-8e46-ee27eff1866d.png)

Ah, Thanks for posting that. I'm not on the discord. but oddly enough I saw you comment with the link to it above and was going to check it out when I got home tonight. But you've just save me that ^^.

But this is good new for me, hopefully keep my friends quite now about asking if there any updates so we can use it😂.
