### ISSUE TITLE
Crash - Cause Unknown, attributed to Rubidium rendering

### ISSUE THREAD

**Issue by AndreDio** [Asek3/Rubidium#686]
Below is the crash report:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-11-11 14:11:29
Description: Encountered exception while building chunk meshes

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Rubidium (rubidium), Version: 0.7.1
		at TRANSFORMER/rubidium@0.7.1/me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340)
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
-- Block being rendered --
Details:
	Block: Block{minecraft:lava}[level=2]
	Block location: World: (91,-38,-167), Section: (at 11,10,9 in 5,-3,-11; chunk contains blocks 80,-64,-176 to 95,319,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Chunk section: RenderSection at chunk (5, -3, -11) from (80, -48, -176) to (95, -33, -161)
	Render context volume: BoundingBox{minX=78, minY=-50, minZ=-178, maxX=97, maxY=-31, maxZ=-159}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23265!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['adiony'/220, l='ClientLevel', x=0.70, y=68.99, z=21.70]]
	Chunk stats: 4096, 705
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,72,0), Section: (at 0,8,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 41433 game time, 46755 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23284!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:rubidium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:rubidium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:rubidium.mixins.json:features.render.world.sky.ClientWorldMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23284!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:tenshilib.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:cold_sweat.mixin.json:MixinPickEntity,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.20.1-20230612.114412-srg.jar%23284!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:tenshilib.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:cold_sweat.mixin.json:MixinPickEntity,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, Moonlight Mods Dynamic Assets

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2595678608 bytes (2475 MiB) / 6392119296 bytes (6096 MiB) up to 10368319488 bytes (9888 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5912
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2111
	Graphics card #1 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 3072.00
	Graphics card #1 deviceId: 0x1c02
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3640
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35335.23
	Virtual memory used (MB): 30824.75
	Swap memory total (MB): 19053.14
	Swap memory used (MB): 2407.90
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9888m -Xms256m
	Launched Version: forge-47.2.5
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.40, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['adiony'/220, l='ServerLevel[Dev A]', x=0.70, y=68.99, z=21.70]]
	Data Packs: vanilla, mod:tenshilib (incompatible), mod:handcrafted (incompatible), mod:terrablender (incompatible), mod:ambientsounds, mod:additionalentityattributes (incompatible), mod:valhelsia_structures (incompatible), mod:geckolib, mod:playeranimator (incompatible), mod:nyctophobia (incompatible), mod:creativecore, mod:botarium (incompatible), mod:bunker_down, mod:animatedquarries, mod:elenaidodge2, mod:resourcefulconfig (incompatible), mod:calio, mod:caelus (incompatible), mod:valhelsia_furniture (incompatible), mod:feathers, mod:apoli (incompatible), mod:origins (incompatible), mod:experienceobelisk (incompatible), mod:sereneseasons (incompatible), mod:sereneseasonfix (incompatible), mod:mixinextras (incompatible), mod:resourcefullib (incompatible), mod:architectury (incompatible), mod:lootr, mod:terralith, mod:cold_sweat (incompatible), mod:cloth_config (incompatible), mod:simplyswords (incompatible), mod:bettercombat (incompatible), mod:sound_physics_remastered, mod:forge, mod:improvedmobs (incompatible), mod:valhelsia_core (incompatible), mod:ad_astra (incompatible), mod:tempad (incompatible), mod:elytraslot (incompatible), mod:dynamiclightsreforged (incompatible), mod:betterdungeons, mod:jei, mod:rubidium, mod:waystones, mod:clumps (incompatible), mod:journeymap (incompatible), mod:yungsapi, mod:laserbridges (incompatible), mod:starlight (incompatible), mod:balm, mod:jeresources, mod:supplementaries, mod:okzoomer (incompatible), mod:farmersdelight, mod:moonlight (incompatible), mod:mixinsquared (incompatible), mod:jade (incompatible), mod:recipes_lib, mod:spark (incompatible), mod:manyideas_core, mod:curios (incompatible), mod:cullleaves (incompatible), mod:midnightlib (incompatible), mod:entityculling, mod:manyideas_doors, mod:cfm, mod:aiimprovements, mod:bettermineshafts, mod:mcwlights, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		elytraslot-forge-6.3.0+1.20.1.jar                 |Elytra Slot                   |elytraslot                    |6.3.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		dynamiclightsreforged-1.20.1_v1.6.0.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.20.1_v1.6.0       |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.20-Forge-4.0.3.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		additionalentityattributes-forge-1.4.0.5+1.20.1.ja|Additional Entity Attributes  |additionalentityattributes    |1.4.0.5+1.20.1      |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.2.4.jar                   |GeckoLib 4                    |geckolib                      |4.2.4               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		Nyctophobia_1.6_(FORGE)_for_1.20+.jar             |Nyctophobia                   |nyctophobia                   |1.6                 |DONE      |Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.2.1.jar                   |Botarium                      |botarium                      |2.2.1               |DONE      |Manifest: NOSIGNATURE
		animated_quarries_1.01_1.20.1.jar                 |AnimatedQuarries              |animatedquarries              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		caelus-forge-3.1.0+1.20.jar                       |Caelus API                    |caelus                        |3.1.0+1.20          |DONE      |Manifest: NOSIGNATURE
		valhelsia_furniture-forge-1.20.1-1.1.2.jar        |Valhelsia Furniture           |valhelsia_furniture           |1.1.2               |DONE      |Manifest: NOSIGNATURE
		feathers-1.1.jar                                  |Feathers                      |feathers                      |1.1                 |DONE      |Manifest: NOSIGNATURE
		apoli-forge-1.20.1-2.9.0.2.jar                    |Apoli                         |apoli                         |1.20.1-2.9.0.2      |DONE      |Manifest: NOSIGNATURE
		rubidium-mc1.20.1-0.7.1.jar                       |Rubidium                      |rubidium                      |0.7.1               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.2.jar                   |Waystones                     |waystones                     |14.0.2              |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.3.jar                  |Clumps                        |clumps                        |12.0.0.3            |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.16-forge.jar                |Journeymap                    |journeymap                    |5.9.16              |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.46.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.46            |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.2.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.2    |DONE      |Manifest: NOSIGNATURE
		laserbridges-1.20.1-0-forge.jar                   |LaserBridge                   |laserbridges                  |1.20.1-0-forge      |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-rc.3.jar                  |MixinExtras                   |mixinextras                   |0.2.0-rc.3          |DONE      |Manifest: NOSIGNATURE
		starlight-1.1.2+forge.1cda73c.jar                 |Starlight                     |starlight                     |1.1.2+forge.1cda73c |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.1.4.jar                       |Balm                          |balm                          |7.1.4               |DONE      |Manifest: NOSIGNATURE
		Terralith_1.20.2_v2.4.8.jar                       |Terralith                     |terralith                     |2.4.8               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.238.jar          |Just Enough Resources         |jeresources                   |1.4.0.238           |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.20.1-1.1.2.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.1.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.5-universal.jar                 |Forge                         |forge                         |47.2.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		supplementaries-1.20-2.6.19.jar                   |Supplementaries               |supplementaries               |1.20-2.6.19         |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tenshilib-1.20.1-1.7.2-forge.jar                  |TenshiLib                     |tenshilib                     |1.20.1-1.7.2        |DONE      |Manifest: NOSIGNATURE
		okzoomer-forge-1.20-3.0.1.jar                     |OkZoomer                      |okzoomer                      |3.0.1               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		handcrafted-forge-1.20.1-3.0.5.jar                |Handcrafted                   |handcrafted                   |3.0.5               |DONE      |Manifest: NOSIGNATURE
		tempad-forge-1.20.1-2.1.1.jar                     |Tempad                        |tempad                        |2.1.1               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.8.60-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.8.60         |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.3.1_mc1.20.1.jar           |AmbientSounds                 |ambientsounds                 |5.3.1               |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.8.1+1.20.1.jar               |Better Combat                 |bettercombat                  |1.8.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.6.3.jar                      |Jade                          |jade                          |11.6.3              |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-forge-1.20.1-1.1.0.jar       |Valhelsia Structures          |valhelsia_structures          |1.20.1-1.1.0        |DONE      |Manifest: NOSIGNATURE
		sereneseasonfix-1.20.1-1.0.8.jar                  |Sereneseasonfix               |sereneseasonfix               |1.20.1-1.0.8        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.9_mc1.20.1.jar           |CreativeCore                  |creativecore                  |2.11.9              |DONE      |Manifest: NOSIGNATURE
		bunker-down 1-1-6 - 1-20-1.jar                    |Bunker Down                   |bunker_down                   |1.1.6               |DONE      |Manifest: NOSIGNATURE
		elenaidodge2-1.1.jar                              |Elenai Dodge                  |elenaidodge2                  |1.1                 |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.0.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.0               |DONE      |Manifest: NOSIGNATURE
		RecipesLibrary-1.20.1-2.0.1.jar                   |Recipes Library               |recipes_lib                   |2.0.1               |DONE      |Manifest: NOSIGNATURE
		calio-forge-1.20.1-1.11.0.1.jar                   |Calio                         |calio                         |1.20.1-1.11.0.1     |DONE      |Manifest: NOSIGNATURE
		spark-1.10.53-forge.jar                           |spark                         |spark                         |1.10.53             |DONE      |Manifest: NOSIGNATURE
		ManyIdeasCore-1.20.1-1.4.2.jar                    |ManyIdeas Core                |manyideas_core                |1.4.2               |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.4.2+1.20.1.jar                     |Curios API                    |curios                        |5.4.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		origins-forge-1.20.1-1.10.0.2-all.jar             |Origins                       |origins                       |1.20.1-1.10.0.2     |DONE      |Manifest: NOSIGNATURE
		cullleaves-forge-3.2.0.jar                        |CullLeaves                    |cullleaves                    |3.2.0               |DONE      |Manifest: NOSIGNATURE
		midnightlib-forge-1.4.1.jar                       |MidnightLib                   |midnightlib                   |1.4.1               |DONE      |Manifest: NOSIGNATURE
		experienceobelisk-v1.4.10-1.20.1.jar              |Experience Obelisk            |experienceobelisk             |1.4.10-1.20.1       |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.6.2-mc1.20.1.jar            |EntityCulling                 |entityculling                 |1.6.2               |DONE      |Manifest: NOSIGNATURE
		ManyIdeasDoors-1.20.1-1.2.3.jar                   |ManyIdeas Doors               |manyideas_doors               |1.2.3               |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.16.jar            |Resourceful Lib               |resourcefullib                |2.1.16              |DONE      |Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		simplyswords-forge-1.51.5-1.20.1.jar              |Simply Swords                 |simplyswords                  |1.51.5-1.20.1       |DONE      |Manifest: NOSIGNATURE
		lootr-1.20-0.7.30.73.jar                          |Lootr                         |lootr                         |0.7.29.68           |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.20-0.5.2.jar                    |AI-Improvements               |aiimprovements                |0.5.2               |DONE      |Manifest: NOSIGNATURE
		ColdSweat-2.2.2.jar                               |Cold Sweat                    |cold_sweat                    |2.2.2               |DONE      |Manifest: NOSIGNATURE
		improvedmobs-1.20.1-1.11.6-forge.jar              |Improved Mobs Mod             |improvedmobs                  |1.20.1-1.11.6       |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.20-Forge-4.0.4.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-forge-1.20.1-1.1.1.jar             |Valhelsia Core                |valhelsia_core                |1.1.1               |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.6-mc1.20.1forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
		ad_astra-forge-1.20.1-1.15.4.jar                  |Ad Astra                      |ad_astra                      |1.15.4              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e059dd66-faa0-4549-a120-e18ea4cdee64
	FML: 47.2
	Forge: net.minecraftforge:47.2.5

**Comment by RexVizsla** [comment]
Same issue, Crash-Log looks the same except that I have Forge version 47.2.4

**Comment by NumpaMC** [comment]
I also encountered the same situation.

**Comment by Port06** [comment]
It appears to be lava rendering, the auther knows about it already. Hope he isn't that long to fix this but already been 2 weeks

**Comment by SoftboyMC** [comment]
open a new world, place lava, place glass next to it. same issue?

**Comment by Natetromino** [comment]
> open a new world, place lava, place glass next to it. same issue?

I also have this issue, testing it in a superflat, lava by itself wont crash the game, but surrounding in glass does. Hopefully it gets resolved soon.

**Comment by 1luik** [comment]
What mods do you have? I have installed 430 mods and encountered the same problem with all of them, making it impossible to fix. This way, I can narrow down the scope of the issue. Thank you very much.

**Comment by FuzzyFoxe** [comment]
> open a new world, place lava, place glass next to it. same issue?

Yep, same here. I wonder if it has something to do with rendering the side of lava through a transparent full block?
(I've also tried disabling some options in video settings to no avail. Guess I gotta avoid transparent blocks and lava for now)

**EDIT:** Using Embeddium for Neoforge, it seems that this issue isn't effecting it.

**Comment by SniperGuaxiNoob** [comment]
tested the Lava method and worked (unfortunately)
this is really bad bcause I can't enter in my world anymore :) Its crashes immediatelly and if I unistall the mod I still cant play because my 60 - 52 fps (with Rubidium) goes to 5 - 10 fps!! (without)
