### ISSUE TITLE
Bug with LittleTiles

### ISSUE THREAD

**Issue by Auleiy** [Asek3/Rubidium#743]
Only rendering the chunks that don't have littletiles block. No any unusual in log, but always send the following exception extremely quickly on console:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.BlockAndTintGetter.m_8055_(net.minecraft.core.BlockPos)" because "this.level" is null
        at TRANSFORMER/embeddium@0.3.31+mc1.20.1/org.embeddedt.embeddium.render.chunk.light.ForgeLightPipeline.computeLightData(ForgeLightPipeline.java:54)
        at TRANSFORMER/embeddium@0.3.31+mc1.20.1/org.embeddedt.embeddium.render.chunk.light.ForgeLightPipeline.calculate(ForgeLightPipeline.java:75)
        at TRANSFORMER/littletiles@1.6.0-pre131/team.creative.littletiles.client.mod.rubidium.pipeline.LittleRenderPipelineRubidium.buildCache(LittleRenderPipelineRubidium.java:184)
        at TRANSFORMER/littletiles@1.6.0-pre131/team.creative.littletiles.client.render.cache.build.RenderingThread.run(RenderingThread.java:233)
```

**Comment by Amateur233** [comment]
Use Embeddium instead, like Rubidium has been dead for a year by far. Thank you.

**Comment by Amateur233** [comment]
https://github.com/Asek3/Rubidium/issues/737
